server:
  port: 20000
spring:
  application:
    name: PLOUFCOURS
  data:
    mongodb:
      database: base2
      host: localhost
      port: 27017
      username: root
      password: root
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30000/eureka/


logging:
    level:
      org.springframework.web: INFO